import { Banner } from '../models/layout/banner.model';

export const HOME_BANNERS: Banner[] = [
  {
    id: 1,
    orden: 1,
    titulo: 'Cortes modernos',
    subtitulo: 'Estilo y precisión en cada detalle',
    activo: true,
    urlImagen: '/assets/homepage.jpg',
    urlDestino: '/reservas',
    seccion: 'HOME_TOP',
    fechaInicio: null,
    fechaFin: null,
  },
  {
    id: 2,
    orden: 2,
    titulo: 'Barbería clásica',
    subtitulo: 'La experiencia Fadex para tu mejor versión',
    activo: true,
    urlImagen: '/assets/homepage.webp',
    urlDestino: '/reservas',
    seccion: 'HOME_TOP',
    fechaInicio: null,
    fechaFin: null,
  },
  {
    id: 3,
    orden: 3,
    titulo: 'Cuidado de barba',
    subtitulo: 'Detalles que definen tu estilo',
    activo: true,
    urlImagen: '/assets/cortebarba.jpg',
    urlDestino: '/reservas',
    seccion: 'HOME_TOP',
    fechaInicio: null,
    fechaFin: null,
  },
];
