export enum EstadoReserva {
    PENDIENTE_PAGO = "PENDIENTE_PAGO",
    CONFIRMADA = "CONFIRMADA",
    EN_PROCESO = "EN_PROCESO",
    FINALIZADA = "FINALIZADA",
    CANCELADA = "CANCELADA",
    CANCELADA_AUTOMATICA = "CANCELADA_AUTOMATICA",
    NO_ASISTIO = "NO_ASISTIO"
}